### PR TITLE
Adding net/url PathEscape to string variables

### LINKED ISSUE #150: escaping the path in URL's
Hi,

I've noticed that on a few places you've chosen to add arguments to the URL, without adding any URL escaping. This unfortunately forces the consumer of e.g.: `mollie.SubscriptionService{}` to know about the underlying transport mechanism and requires them to apply URL escaping prior to calling a service, i.e.:
```go
func (p *provider) CancelRecurringPayment(customerID UserID, subscriptionID string) error {

	// Note: github.com/VictorAvelar/mollie-api-go/v2/mollie does not escape these arguments, so we do it here.
	customerID = url.PathEscape(customerID)
	subscriptionID = url.PathEscape(subscriptionID)

	_, err := p.client.Subscriptions.Delete(customerID, subscriptionID)

	return err
}
```

I realise that the Mollie identifiers commonly don't contain reserved characters, but that's a lof of trust to expect for user of the SDK :-)

<details>

<summary>Other locations</summary>

```text
mollie/captures.go
51:	u := fmt.Sprintf("v2/payments/%s/captures/%s", pID, cID)
72:	u := fmt.Sprintf("v2/payments/%s/captures", pID)

mollie/chargebacks.go
63:	u := fmt.Sprintf("v2/payments/%s/chargebacks/%s", paymentID, chargebackID)
98:	u := fmt.Sprintf("v2/payments/%s/chargebacks", paymentID)

mollie/customers.go
163:	u := fmt.Sprintf("v2/customers/%s/payments", id)
184:	u := fmt.Sprintf("v2/customers/%s/payments", id)

mollie/profiles.go
170:	u := fmt.Sprintf("v2/profiles/%s/methods/%s", id, pm)
188:	u := fmt.Sprintf("v2/profiles/%s/methods/%s", id, pm)
257:	u := fmt.Sprintf("v2/profiles/%s/methods/giftcard/issuers/%s", profileID, issuer)

mollie/mandates.go
104:	u := fmt.Sprintf("v2/customers/%s/mandates", cID)
128:	u := fmt.Sprintf("v2/customers/%s/mandates/%s", cID, mID)
151:	u := fmt.Sprintf("v2/customers/%s/mandates/%s", cID, mID)
170:	u := fmt.Sprintf("v2/customers/%s/mandates", cID)

mollie/shipments.go
46:	u := fmt.Sprintf("v2/orders/%s/shipments/%s", oID, sID)
74:	u := fmt.Sprintf("v2/orders/%s/shipments", oID)
109:	u := fmt.Sprintf("v2/orders/%s/shipments", oID)
130:	u := fmt.Sprintf("v2/orders/%s/shipments/%s", oID, sID)

mollie/subscriptions.go
79:	u := fmt.Sprintf("v2/customers/%s/subscriptions/%s", cID, sID)
100:	u := fmt.Sprintf("v2/customers/%s/subscriptions", cID)
126:	u := fmt.Sprintf("v2/customers/%s/subscriptions/%s", cID, sID)
148:	u := fmt.Sprintf("v2/customers/%s/subscriptions/%s", cID, sID)
193:	u := fmt.Sprintf("v2/customers/%s/subscriptions", cID)
215:	u := fmt.Sprintf("v2/customers/%s/subscriptions/%s/payments", cID, sID)

mollie/refunds.go
85:	u := fmt.Sprintf("v2/payments/%s/refunds/%s", paymentID, refundID)
112:	u := fmt.Sprintf("v2/payments/%s/refunds", paymentID)
143:	u := fmt.Sprintf("v2/payments/%s/refunds/%s", paymentID, refundID)
179:	u := fmt.Sprintf("v2/payments/%s/refunds", paymentID)

mollie/orders.go
348:	u := fmt.Sprintf("v2/orders/%s/lines/%s", orderID, orderLineID)
373:	u := fmt.Sprintf("v2/orders/%s/lines", orderID)
392:	u := fmt.Sprintf("v2/orders/%s/payments", orderID)
414:	u := fmt.Sprintf("v2/orders/%s/refunds", orderID)
436:	u := fmt.Sprintf("v2/orders/%s/refunds", orderID)
```
</details>

### PR DESCRIPTION
**Pull request by Stuie**
## Description

Issue #150 lists multiple places where unescaped variable are used in constructed URLs. I have gone through them all and added `net/url`'s `PathEscape` to each.

## Motivation and context

Passed variables may contain unsafe characters for a request. As such, some users resort to escaping their own variables, requiring knowledge of--and leaking information about--an implementation detail that could conceivably change.

Fixes #150

## How has this been tested?

This change has not been tested at all at this point. I'm posting the draft PR now because I have questions about other variables, and the implications of the change.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our continuous integration server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [ ] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

# Questions from me

1. Should this change require/include some sort of version bump in order to prevent double escaping by users who are currently performing their own escaping?
2. Should some documentation be added to types like `PaymentMethod` that are essentially strings that may be used in constructed URLs so that any future updates to those types will be URL safe? I realize it is unlikely that a payment type will have unsafe characters in, but it's just an example.

### CODE REVIEW

**Comment by VictorAvelar** [comment]
@Stuie if nothing else will change I would like to merge this PR soon, will wait until tomorrow and if nothing changes will move forward. Thanks for your contribution. 🚀

**Comment by Stuie** [comment]
The change is not being tested by the original tests. There we no failures when I changed the behavior.

1. The tests I looked at all have hardcoded response bodies from `testdata.GetCaptureResponse`, so I can't check the content of the body to make sure the URL encoding was performed.
2. The `Captures.Get` method, for example, only returns the body and an error object. It doesn't return the `Request` or `Response` objects so I can't get the URL that was built and confirm that the URL-unsafe characters were encoded.

I don't see how I can test this without changing the signatures.

I would like to point out that now the methods encode URL parameters when they didn't before, so _this is a breaking change_ for anyone who is already encoding their own parameters, like @Dynom's example at the top of #150 

[Check out this demo](https://play.golang.org/p/Ifbfs7J8l5J).

If you have bump the version anyway, then changing the signature to include the response (as long as you can get the Request from that) would make this change testable.

**Comment by VictorAvelar** [comment]
@Stuie you're right, could you please change the target of this PR to v3-dev branch?

**Comment by Dynom** [comment]
> I don't see how I can test this without changing the signatures.

_I hope I'm not over stepping my bounds for making a suggestion. If I do, please just ignore it._

I believe that URL encoding is the responsibility of `mollie.Client`, as that's the only thing that knows about the transport mechanism.

While it might be a bit of refactor, if `*Client.NewAPIRequest()` changes it signature, it makes the escaping centralised and the overall change, quite a bit smaller.

Currently the signature reads:
```go
func (c *Client) NewAPIRequest(method string, uri string, body interface{}) (req *http.Request, err error)
```

## Using a slice instead
Based on what I've seen in the source, `uri` is (currently) always a string path. By changing this to the following signature, we maintain some extra information, which we can use to: centralise escaping and maintain a high degree of flexibility, while keep bloat to a minimum. The advantage here is that you only need to test `NewAPIRequest` for escaping correctness, without testing all service methods.

```go
func (c *Client) NewAPIRequest(method string, pathPaths []string, body interface{}) (req *http.Request, err error)
```

An example implementation, which assumes we'll always deal with paths:
```go
func (c *Client) NewAPIRequest(method string, pathParts []string, body interface{}) (req *http.Request, err error) {
	if !strings.HasSuffix(c.BaseURL.Path, "/") {
		return nil, errBadBaseURL
	}

	u := &url.URL{}
	for _, p := range paths {
		u.Path = path.Join(u.Path, url.PathEscape(p))
	}

	u = c.BaseURL.ResolveReference(u)

	// ..
```

<details>
<summary>An example usage of NewAPIRequest()</summary>

```go
func (cs *CapturesService) Get(pID, cID string) (c *Capture, err error) {
	req, err := cs.client.NewAPIRequest(http.MethodGet, []string{"v2", "payments", pID, "captures", cID}, nil)
	if err != nil {
		return
	}
	res, err := cs.client.Do(req)
	if err != nil {
		return
	}
	if err = json.Unmarshal(res.content, &c); err != nil {
		return
	}
	return
}
```

</details>

Giving it a specific type could prevent future development from making mistakes

## Using the `url.URL` type
Alternatively the signature can be changed to use the `url.URL` type directly. This gives you all the freedom, including overriding the baseURL, which could be useful for testing. However you still need to apply escaping in the services. Using a `url.URL` type here won't improve the ability to testing I suspect. 
```go
func (c *Client) NewAPIRequest(method string, uri *url.URL, body interface{}) (req *http.Request, err error) {
	if !strings.HasSuffix(c.BaseURL.Path, "/") {
		return nil, errBadBaseURL
	}

	u := c.BaseURL.ResolveReference(uri)

	// ..
```

<details>
<summary>An example usage of NewAPIRequest()</summary>

```go
func (cs *CapturesService) Get(pID, cID string) (c *Capture, err error) {
	u := &url.URL{}
	u.Path = path.Join([]string{"v2", "payments", url.PathEscape(pID), "captures", url.PathEscape(cID)}...)

	req, err := cs.client.NewAPIRequest(http.MethodGet, u, nil)
	if err != nil {
		return
	}
	res, err := cs.client.Do(req)
	if err != nil {
		return
	}
	if err = json.Unmarshal(res.content, &c); err != nil {
		return
	}
	return
}
```

</details>

> The Captures.Get method, for example, only returns the body and an error object. It doesn't return the Request or Response objects so I can't get the URL that was built and confirm that the URL-unsafe characters were encoded.

I believe you can inspect `r.url` for `func TestCapturesService_Get(t *testing.T) {` and test for the URL of the request.


Alternatively, instead of accepting a concrete type for `Client.client *http.Client` could be to accept an interface instead. This allows you to stub it out and inspect as you see fit, without needing to start a server.

**Pull request closed without merging**
