### PR TITLE
Fix metadata type

### PR DESCRIPTION
**Pull request by jld3103**
## Description

Changes the `Metadata` field for creating customers and subscriptions from `map[string]interface{}` to `interface{}` which is the correct type according to the docs (https://docs.mollie.com/reference/v2/customers-api/create-customer https://docs.mollie.com/reference/v2/subscriptions-api/create-subscription) and is also used elsewhere in this library.

## Motivation and context

I want to use a string as metadata which is currently not possible.

## How has this been tested?

Not needed, but tested in local deployment and unit tests are passing.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our continuous integration server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by VictorAvelar** [comment]
Hello, sorry for the delay to review your PR.

I have overall only two questions:

1. Are you sure defining metadata as a simple string is not failing when calling the API?
2. Are you using v3 or v2 of the library? I am asking just in case we also need to port the fix to v2.

**Comment by jld3103** [comment]
What do you mean with simple string? It's defined as an `interface{}`. If you look where the Metadata parameter is used elsewhere in this library you see it's also defined as `interface{}`. I'm using the v3 version of the library.

**Comment by VictorAvelar** [comment]
Sorry if I framed my question poorly.

Given the way JSON is interpreted on PHP's side, I wonder (therefore ask) if supplying a string will cause the call to fail on Mollie's side.

Passing 'some random text', for example, will fail since JSON is supposed to begin with `{`, however, parsing a map which is parsed as an object overcomes this issue. But this is just my supposition, and I'd want to know whether you tested it.

**Comment by jld3103** [comment]
Sorry for not being clear. The docs for the Metadata field say `Provide any data you like` (e.g. https://docs.mollie.com/reference/v2/customers-api/create-customer).

**Comment by jld3103** [comment]
And yes I tested that it works. In my case I'm using a string as the Metadata

**Comment by VictorAvelar** [comment]
Ok, perfect. Thanks for following up and for the fix. 😄

**Comment by jld3103** [comment]
Thanks a lot! Could you make a new release?

**Comment by VictorAvelar** [comment]
Done already check [v3.2.0](https://github.com/VictorAvelar/mollie-api-go/releases/tag/v3.2.0)

**Comment by jld3103** [comment]
Thanks!

**Pull request merged**
