### PR TITLE
Add example to for customer and payment

### PR DESCRIPTION
**Pull request by nanikjava**
## Description

Create code samples for customers #74

## Motivation and context

Need more samples

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation / Code samples

### CODE REVIEW

**Comment by VictorAvelar** [comment]
Thanks for the samples @nanikjava . Are you going to also add the `test example` ? 👍🏾

**Review by VictorAvelar — COMMENTED** [review]
Waiting for @nanikjava to know if a test example will be added, also need to make the branch even with the latest master changes.

**Comment by nanikjava** [comment]
> Waiting for @nanikjava to know if a test example will be added, also need to make the branch even with the latest master changes.

Don't think will need a test for this one. The example is sufficient.

**Comment by VictorAvelar** [comment]
I was not speaking about testing the code, I am talking about an example that godoc can render, for example [this one for profiles](https://pkg.go.dev/github.com/VictorAvelar/mollie-api-go/mollie#example-ProfilesService.Get), [here you can check the source code] 😄(https://github.com/VictorAvelar/mollie-api-go/pull/82/files#diff-08c83e6d34455fe8c6fff755ea0d9912e64ca12e355be04d71045d288e3ce235)

**Comment by nanikjava** [comment]
> I was not speaking about testing the code, I am talking about an example that godoc can render, for example [this one for profiles](https://pkg.go.dev/github.com/VictorAvelar/mollie-api-go/mollie#example-ProfilesService.Get), [here you can check the source code](https://github.com/VictorAvelar/mollie-api-go/pull/82/files#diff-08c83e6d34455fe8c6fff755ea0d9912e64ca12e355be04d71045d288e3ce235)

Comparing with the example you mention the comments are all there and godoc should be able to render it.

Let me know if is not able to render it.

**Comment by nanikjava** [comment]
@VictorAvelar will you be able to approve and merge this PR ? Thanks.

**Review by VictorAvelar — APPROVED** [review]

**Pull request merged**
